### ISSUE TITLE
&str is erroneously transformed into `const char *`

### ISSUE THREAD

**Issue by RReverser** [eqrion/cbindgen#82]
If I use `&[u8]` or any other "fat" reference:

```rust
#[no_mangle]
pub extern "C" fn f(s: &[u8]) {}
```

I receive an error message as expected since fat reference is not an ABI-safe type:

> ERROR: Cannot use fn ::f (Unsupported type.).

However, when I use `&str`

```rust
#[no_mangle]
pub extern "C" fn f(s: &str) {}
```

I don't receive a similar error, and instead get `const char *` generated:

```c
#include <cstdint>
#include <cstdlib>

extern "C" {

void f(const char *s);

} // extern "C"
```

This is incorrect and extremely unsafe since it suggests that C side can just pass a raw pointer (to string bytes), while Rust side will also try to read invalid memory as the size part of the fat pointer (since `&str` is essentially the same as `&[u8]` not counting the UTF-8 guarantee, and must be treated in exactly same way across FFI boundary).

**Comment by eqrion** [comment]
Yes, you're right this is incorrect and very unsafe. This was erroneously enabled from my work with `static` and `const`, and should be fixed.

**Comment by eqrion** [comment]
This should be fixed in `0.2.1`. Please reopen if this is still an issue.

**Comment by RReverser** [comment]
@eqrion Can't reopen the issue, but this seems to be still a problem for static items. In particular, `static.rs` test contains following expression which Rust even complains due to type mismatch:

```rust
static STRING: &'static libc::c_char = "hello world";
```

Exporting string via static variable here is just as unsafe as using it anywhere in functions.

**Comment by eqrion** [comment]
@RReverser Looking into this again, is the problem just with this test? I can confirm it's poorly written as it's not valid rust. cbindgen can't protect against this case because the problem is with the right hand of the assignment, and the type tells it to emit a `const char*`.

Are there any other cases we emit `const char*` when we should not?

**Comment by eqrion** [comment]
I'm going to close this now as the original issue was fixed. Let's open a new issue if there are still cases where we export invalid types in const/static.
